spring.application.name=sentinel
server.port=6060

spring.datasource.url=jdbc:sqlite:db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.datasource.initialization-mode=always
spring.sql.init.mode=always


## project config
sentinel.version=1.0.0

sentinel.processor.docker.cert_path=/Users/hancher/work/temp/certs

# sentinel.processor.docker.host-certs[tcp://192.168.1.1:2376]=/path/to/certs-a
# sentinel.processor.docker.host-certs[tcp://192.168.1.2:2376]=/path/to/certs-b
sentinel.processor.docker.max_idle_minutes=30


# dev auto reload
#spring.thymeleaf.cache=false
#spring.devtools.restart.enabled=true
#spring.devtools.livereload.enabled=true
